openapi: 3.0.3
info:
  title: Flee Backend API - OpenAPI 3.0
  description: Flee Backend API Documentation
  contact:
    email: tharunvind@gmail.com
  version: 1.0.1
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: Permit
    description: Everything about Permit
  - name: User
    description: Everything about User
  - name: System
    description: Everything about System

paths:
  /populate/outpass/create:
    post:
      tags:
        - Permit
      security:
        - bearerAuth: []
      summary: Creates a new outpass
      description: This API  creates a new outpass. This API is consumed by the student component. It requires Student JWT. 
      requestBody:
        description: creates a new pass
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - name
                - phoneNumber
                - outTime
                - inTime
                - inVerified
                - outVerified
                - purpose
              properties:
                id:
                  type: string
                  example: 2020bcs0066
                name:
                  type: string
                  example: Tharun Vemula
                phoneNumber:
                  type: string
                  example: '6301930763'
                outTime:
                  type: string
                  example: '2023-02-11T18:30:00.000Z'
                inTime:
                  type: string
                  example: '2023-02-11T18:30:00.000Z'
                purpose:
                  type: number
                  example: 0
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permit'

  /populate/outpass/verify:
    put:
      tags:
        - Permit
      security:
        - bearerAuth: []
      summary: Verifies Outpass at the Security
      description: InVerification and OutVerification API. This API is consumed by the Security Component. It requries Security JWT.
      requestBody:
        description: verifies a new pass
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: <ObjectID>
                type:
                  type: number
                  example: 0
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permit'
        '400':
          description: Invalid status value

  /populate/student/remark:
    put:
      tags:
        - User
      security:
        - bearerAuth: []
      summary: Increments remark of a user
      description: Increments Remarks score by 1.
      requestBody:
        description: Increments Remarks score by 1 of a student.
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: 2020bcs0066
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Invalid tag value

  /populate/student/outgoing:
    get:
      tags:
        - Permit
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: date
          schema:
            type: string
          required: true
          description: date on which outpasses should be fetched
        - in: path
          name: hostel
          schema:
            type: string
          required: true
          description: date on which outpasses should be fetched 


      summary: Fectches all outpasses between from - to date and also of a particular hostel.
      description: Returns an array of Students going out in between dates. This API is consumed by the Security Component or Warden Component. It requires Security JWT | Warden JWT
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Permit'
        '400':
          description: Invalid ID supplied
        '404':
          description: Permit not found

  /auth/login:
    post:
      tags:
        - Auth
      security:
        - bearerAuth: []
      summary: Authenticates an User
      description: Returns a payload containing user data
      requestBody:
        description: Returns a payload containing user data
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: 2020bcs0066
                password:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                    example: theUser
                  password:
                    type: string
                    example: '12345'
                  role:
                    type: number
                    example: 0
                xml:
                  name: user
  /system:
    get:
      tags:
        - System
      summary: get status of the system
      description: Returns the status of the System. It is an open API.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/System'

  /admin/system:
    put:
      tags:
        - System
      security:
        - bearerAuth: []
      summary: sets the status of the system. Admin can alter the properties of the system
      description: Returns the status of the System. Only the admin can consume the API. It requires Admin JWT
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/System'

  /populate/student/profile:
    get:
      tags:
        - User
      security:
        - bearerAuth: []
      summary: fetches previous outpass data of a user
      description: Returns the user data. Used for refreshing. This API is consumed by the Student Component. It requires Student JWT.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Permit'
                xml:
                  name: permit

  /populate/student/allowance:
    get:
      tags:
        - User
      security:
        - bearerAuth: []
      summary: get the student status - Internal API
      description: Internal API to check the status of student. Returns a boolean that indicates if the student can request auto generated outpass.This API is consumed by the Student Component. It requires Student JWT.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                xml:
                  name: user


  /populate/student/status:
    put:
      tags:
        - User
      security:
        - bearerAuth: []
      summary: Sets status for a student
      description: Warden can set status to a student. This API is consumed by Warden Component. It requires Warden JWT.
      requestBody:
        description: Returns a payload containing user data
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: 2020bcs0066
                status:
                  type: boolean
                  example: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        default:
          description: successful operation

  /populate/student/history:
    get:
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: id of the student to be fetched
      summary: gets history of a student
      description: Warden can view history of a student. This API is consumed by Warden Component. It requires Warden JWT.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        default:
          description: successful operation

  /populate/student/location:
    get:
      tags:
        - User
      security:
        - bearerAuth: []
      summary: gets current location of a student
      description: gets current location of a student . In - 0 / Out - 1. It requires Student JWT.
      responses:
        '200':
          description: Returns an object with only key, status set to either 0 or 1
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
        default:
          description: successful operation

  # /populate/hostel/student/outgoing:
  #   post:
  #     tags:
  #       - Permit
  #     security:
  #       - bearerAuth: []
  #     summary: Fectches Students from - to date of a particular hostel under warden.
  #     description: Returns an array of Students going out in between dates. This API is consumed by the Warden Component. It requires Warden JWT
  #     requestBody:
  #       description: Returns an array of Students going out in between dates
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               date:
  #                 type: string
  #                 example: '2011-10-05T14:48:00.000Z'
  #               hostel:
  #                 type: string
  #                 example: 'h2'
  #     responses:
  #       '200':
  #         description: successful operation
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: '#/components/schemas/Permit'
  #       '400':
  #         description: Invalid ID supplied
  #       '404':
  #         description: Permit not found

  /populate/hostel/outpass/approve:
    post:
      tags:
        - Permit
      security:
        - bearerAuth: []
      summary: Verifies Pending Verification Outpasses
      description: Approves/Rejects outpasses that are not auto approved
      requestBody:
        description: verifies a new pass
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: <ObjectID>
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permit'
        '400':
          description: Invalid status value

  /populate/hostel/student:
    get:
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: q
          schema:
            type: string
          required: true
          description: what query it is q = blocked || all
        - in: path
          name: hostel
          schema:
            type: string
          required: true
          description: date on which outpasses should be fetched 
      summary: Fectches blacklisted or all students based on query
      description: Returns an array of blacklisted or all Students of that hostel It requires Warden JWT
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
        '400':
          description: Invalid ID supplied
        '404':
          description: Permit not found

  /populate/hostel/outpass/pending:
    get:
      tags:
        - Permit
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: hostel
          schema:
            type: string
          required: true
          description: date on which outpasses should be fetched 
      summary: Fectches pending outpasses
      description: Returns an array of outpasses whose approval is pending.It requires Warden JWT
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Permit'
        '400':
          description: Invalid ID supplied
        '404':
          description: Permit not found
  /populate/outpass/delete:
    delete:
      tags:
        - Permit
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: id of the outpass to be ddeleted
      summary: deletes the selected outpass
      description: Returns an acknowledgment of the deleted outpass
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Permit not found

  /populate/fp/scan:
    post:
      tags:
        - Fingerprint
      summary: API Call made by Fingerprint module
      description: API Call made by Fingerprint module
      requestBody:
        description: verifies a new pass
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: '2020bcs0066'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permit'
        '400':
          description: Invalid status value

components:
  schemas:
    Permit:
      type: object
      required:
        - id
        - name
        - phoneNumber
        - outTime
        - inTime
        - isInVerified
        - isOutVerified
        - purpose
        - hostel
      properties:
        id:
          type: string
          example: 2020bcs0066
        name:
          type: string
          example: Tharun Vemula
        phoneNumber:
          type: string
          example: '6301930763'
        outTime:
          type: string
          example: '2023-02-11T18:30:00.000Z'
        verifiedOutTime:
          type: string
          example: '2023-02-11T18:30:00.000Z'
        verifiedInTime:
          type: string
          example: '2023-02-11T18:30:00.000Z'
        inTime:
          type: string
          example: '2023-02-11T18:30:00.000Z'
        isInVerified:
          type: boolean
          example: false
        isOutVerified:
          type: boolean
          example: false
        purpose:
          type: number
          example: 0
        inApprovedBy:
          type: string
          example: Security 1
        outApprovedBy:
          type: string
          example: Security 1
        hostel:
          type : string 
          example : h2
    User:
      type: object
      required:
        - id
        - name
        - password
        - role
      properties:
        id:
          type: string
        name:
          type: string
          example: theUser
        password:
          type: string
          example: '12345'
        role:
          type: number
          example: 0
      xml:
        name: user

    Student:
      allOf:
        - ref: '#/components/schema/User'
        - type: object
          required:
            - status
            - remarkScore
            - hostel
            - gender
            - inCampus
          properties:
            status:
              type: boolean
              example: true
            remarkScore:
              type: number
              example: 0
            hostel:
              type: string
              example: h2
            gender:
              type: string
              example: male
            inCampus:
              type: number
              example: 0
    Security:
      allOf:
        - ref: '#/components/schema/User'
        - type: object

    Admin:
      allOf:
        - ref: '#/components/schema/User'
        - type: object

    Warden:
      allOf:
        - ref: '#/components/schema/User'
        - type: object
          required:
            - hostel
          properties:
            hostel:
              type: string
              example: h1
    System:
      type: object
      properties:
        id:
          type: number
          example: 34
        allowOutpass:
          type: boolean
          example: true
        threshold:
          type: number
          example: 3
        allowLeaves:
          type: boolean
          example : false
        outpassIssuanceStartTimeInHours: 
          type: number
          example : 7
        outpassIssuanceEndTimeInHours:
          type: number
          example : 19
        cutOffTImeInHours:
          type: number
          example : 21
        lastUpdated :
          type: string
          example: '2023-02-11T18:30:00.000Z'
